name: Apache Test

on:
  push:
    branches:
      - main

jobs:
  test-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apache
        run: |
          sudo apt update
          sudo apt install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2

      - name: Copy HTML files
        run: |
          sudo cp index.html /var/www/html/index.html

      - name: Test Apache locally
        run: |
          curl http://localhost/index.html
